### PR TITLE
Add new exercise Rotational Cipher

### PR DESCRIPTION
**Pull request by CRivasGomez**
Hello!
I added Rotational Cipher exercise 🙂

### CODE REVIEW

**Comment by matthewmorgan** [comment]
@CRivasGomez thank you for your contribution!

At the moment, the build is not succeeding.  It appears there are a number of [formatting-related issues](https://travis-ci.org/exercism/javascript/builds/347000711#L1369) identified by our linting library.  

If you run the command `npm run lint` locally, you can see the error messages, and correct the formatting to pass linting.

If you need any assistance, please don't hesitate to ask, we're happy to help.

**Comment by CRivasGomez** [comment]
Hey @matthewmorgan ! I was just pushing fixes now 🙂

**Comment by matthewmorgan** [comment]
OK great.  Let me pull down your branch and check it against the canonical tests, and I can give you feedback.  I'll get to this ASAP, but it may be tomorrow morning.

**Comment by matthewmorgan** [comment]
OK, looks great.  Nice work!

**Pull request merged**
