### PR TITLE
Add task description for clarity

### PR DESCRIPTION
**Pull request by critesjosh**
When I first started this assignment, I wasn't exactly sure what to do. I had to look at the tests to see what was expected, so I added a task description for clarity.

Also, just getting familiar with contributing to the project 😃

### CODE REVIEW

**Comment by SleeplessByte** [comment]
Great line. It should be added to the hints file and then the readme should be re-generated. See the CONTRIBUTING guide how to.

**Comment by paparomeo** [comment]
I think this extra clarification would benefit _all_ the tracks, @critesjosh. Did you consider submitting this change to the [`problem-specifications`](https://github.com/exercism/problem-specifications/blob/master/exercises/resistor-color/description.md) repository instead, which would mean it would propagate to all the tracks?

**Comment by SleeplessByte** [comment]
Pingin @critesjosh

**Comment by critesjosh** [comment]
Sorry I've been MIA. I will not likely get to this soon.

**Comment by tejasbubane** [comment]
https://github.com/exercism/problem-specifications/pull/1645 was added to `problem-specifications`. I have raised https://github.com/exercism/javascript/pull/843 to reflect the changes here.

**Comment by tejasbubane** [comment]
I think this can be closed in favor of #843

**Pull request closed without merging**
