### PR TITLE
Added new exercise: tournament

### PR DESCRIPTION
**Pull request by lpizzinidev**
Addresses #926

### CODE REVIEW

**Comment by SleeplessByte** [comment]
Sweet. Thanks @lpizzinidev ! We will check it out and let you know if there are requested changes. Do you happen to be on our slack as well?

**Comment by SleeplessByte** [comment]
(sorry, wrong label attached!)

**Comment by lpizzinidev** [comment]
@SleeplessByte No problem! No, I'm not on your slack.

**Review by junedev — APPROVED** [review]
Looks good overall! I left some thoughts regarding the readability of the test cases.

**Comment by lpizzinidev** [comment]
@junedev Applied suggested changes for test readability and resolved `config.json` conflict.

**Comment by junedev** [comment]
Thanks for the fixes!

**Pull request merged**
