### PR TITLE
Minor fix

### PR DESCRIPTION
**Pull request by qweered**
corresponding https://github.com/exercism/javascript/blob/main/exercises/concept/elyses-enchantments/.docs/instructions.md

### CODE REVIEW

**Comment by junedev** [comment]
@qweered Can you say a couple of words why you think this change is necessary? `newCard` in the instructions is just a variable name so there is no actual need for the two names to match.

**Comment by qweered** [comment]
@junedev I think it removes any misunderstanding like "what is replacement card?". Cause everywhere in code it names newCard

**Comment by SleeplessByte** [comment]
It would become:

````markdown
## 2. Exchange a card in the stack

Perform some sleight of hand and exchange the card at index `position`
with the replacement card provided.
Return the adjusted stack.

```javascript
const position = 2;
const replacementCard = 6;
setItem([1, 2, 4, 1], position, replacementCard);
// => [1, 2, 6, 1]
````

## 2. Exchange a card in the stack

Perform some sleight of hand and exchange the card at index `position`
with the replacement card provided.
Return the adjusted stack.

```javascript
const position = 2;
const replacementCard = 6;
setItem([1, 2, 4, 1], position, replacementCard);
// => [1, 2, 6, 1]

**Comment by qweered** [comment]
Sounds good

**Comment by qweered** [comment]
i think its ready to merge

**Review by SleeplessByte — APPROVED** [review]
Thanks for the change!

**Pull request merged**
