### PR TITLE
[Space Age] Make list consistent, put Earth in proper order

### PR DESCRIPTION
**Pull request by yyyc514**
Sorry, this was driving me nuts.

### CODE REVIEW

**Comment by tejasbubane** [comment]
We try to be consistent with [canonical data](https://github.com/exercism/problem-specifications/blob/00dda3a9f5e7aa5a15d5db36535ae9320d840441/exercises/space-age/description.md). Also there are [specs](https://github.com/exercism/javascript/blob/427d409972d8701c7fec858a42cec7b4487e58c9/exercises/space-age/space-age.spec.js) with the same ordering. `Earth` is the base case, so I am not sure if we should change this.

**Comment by yyyc514** [comment]
I can make a PR against canonical if needed. I’m not sure why the _order_ of the specs should affect the writing of the instructions.  That seems entirely irrelevant.

**Comment by yyyc514** [comment]
https://github.com/exercism/problem-specifications/pull/1573

**Comment by yyyc514** [comment]
> Earth is the base case

Just saw this.  **Not sure I agree.**  Seconds aren't unique to earth.  The input is in seconds.  **Given an age in seconds find your age on any planet.**  _Earth is not a base case._  Often students even go so far as to prove this by removing the common "earth_year_in_seconds" constant that so many choose to use.

 I don't think that needs have any bearing on its ordering in the instructions list.

**Pull request merged**
