### PR TITLE
Cross-platform make 

### PR DESCRIPTION
**Pull request by SleeplessByte**
These changes make sure the paths are escaped properly when on Windows.

(waiting on Travis to see if this builds on linux as I don't have that laptop with me today).

**Edit:** It's failing somewhere but I don't know where XD

### CODE REVIEW

**Comment by tejasbubane** [comment]
Changes seem good to me, but travis is not happy.

**Comment by SleeplessByte** [comment]
Probably something that doesn't work in that shell 💥 . @tejasbubane could you also run these locally? Perhaps I did something stupid 😅

**Comment by tejasbubane** [comment]
@SleeplessByte I could reproduce the error on Mac and here is my fix: https://github.com/exercism/javascript/commit/7557c91f483c2c2dbc6fb1d8fe475ceb276201d2

**Comment by SleeplessByte** [comment]
You're the best @tejasbubane! Thank you. Apparently that is one that _only_ works on windows!

**Comment by tejasbubane** [comment]
> Apparently that is one that _only_ works on windows!

You mean my fix breaks on windows?

**Comment by SleeplessByte** [comment]
@tejasbubane , nah your fix works everywhere, but what it was before only works on windows.

**Comment by SleeplessByte** [comment]
Thanks @tejasbubane for your quick fix 💯

**Pull request merged**
