### PR TITLE
simple-cipher linting issues resolved

### PR DESCRIPTION
**Pull request by cybernetck**
Simple-cipher linting resolved -

screen shot 2018-03-04 at 10 25 28 pm

### CODE REVIEW

**Comment by matthewmorgan** [comment]
@cybernetck thanks for your contribution!

At the moment, the CI build is failing.  Please have a look at the Travis logs, lines 1227 and following: https://travis-ci.org/exercism/javascript/builds/349504707#L1227

Let me know if you need help resolving the build issues.

Also, we don't want to upgrade any versions of dependencies (EG EsLint, Jasmine) as part of this PR.  Changes like that should be in their own PR.

**Comment by cybernetck** [comment]
Thank you for the update @matthewmorgan; I'm going to take a look.  I'll give it another try, and will reach out for support if this next round of review isn't fruitful.

**Comment by matthewmorgan** [comment]
@cybernetck any progress here?  Can I help in any way?

**Comment by matthewmorgan** [comment]
@cybernetck since we haven't heard from you I'm going to close the PR.  Please note that we've since received another PR that passed review for the same exercise, sorry about that.

Don't let this discourage you from getting involved in the future-- we'd love to have your help!

**Pull request closed without merging**
