### PR TITLE
simple-cipher: Update tests according to the spec

### PR DESCRIPTION
**Pull request by pawamoy**
EDIT: at first, this PR just fixed a typo. In the end we updated the test file to match the spec file mentioned in the next comment.

### CODE REVIEW

**Comment by SleeplessByte** [comment]
You're absolutely right. It should actually be updated according to https://github.com/exercism/problem-specifications/blob/master/exercises/simple-cipher/canonical-data.json#L81.

Would you be able to do that? (And update the other test-cases as well)? You can then also make the `package.json` version be `2.0.0`, as long as all the tests match ones from that problem-description repo.

**Comment by pawamoy** [comment]
I can do that. I compared the problem specification and the test file, and there are test cases in the test file that are not in the specification file (`generates keys at random` and `has a key that is at least 100 characters long`, and the whole section about throwing errors when the key is incorrect). I guess I do not have to change the specification, only make sure the actual test cases have the same descriptions?

**Comment by SleeplessByte** [comment]
> , and the whole section about throwing errors when the key is incorrect

yes, they were removed!

> I guess I do not have to change the specification, only make sure the actual test cases have the same descriptions?

Correct! Sync OUR tests with THAT canonical data 🗡

**Comment by pawamoy** [comment]
Alright! I'll remove the extra tests that do not appear in the problem spec then!

**Comment by SleeplessByte** [comment]
The generator that I'm still working on will by default copy paste whatever is in there. 

In this case, I actually don't feel that the `ie. jdjdjdjdjd` stuff adds much value. I would _suggest_ you keep the lowercase (for now) and if you want add the `ie. jdjdjdjdjd` as a comment above/inside the test :)

**Comment by pawamoy** [comment]
Done. I think I've implemented all your comments now :slightly_smiling_face: Let me know if there's anything else!

**Comment by SleeplessByte** [comment]
You're the best! @pawamoy

**Pull request merged**
