### PR TITLE
Convert scripts to ES6

### PR DESCRIPTION
**Pull request by tejasbubane**
Use [@babel/node](https://babeljs.io/docs/en/babel-node) to run them.

Also fix comments in scripts.

### CODE REVIEW

**Comment by tejasbubane** [comment]
> Any reason you changed from function declaration to "assignment pattern" + arrow function expression? I know it's mostly a stylistic choice, but I think the explicit `function` reads better

Nothing specific. My personal preference of the shiny arrow function over normal `function`. I will change it back to `function`.

>  if you're not re-assigning variables, can you use `const` instead of `let`?

Makes sense. 👍

**Comment by SleeplessByte** [comment]
I don't mind the `const x = () => {}`, but I think it helps our junior contributors if it's _more straightforward_ 🗡  I generally use `function` at the top level, and expression everywhere else.

**Comment by tejasbubane** [comment]
@SleeplessByte Fixed.

**Comment by SleeplessByte** [comment]
I think this means we can now do https://github.com/exercism/javascript/issues/628 ?

**Comment by tejasbubane** [comment]
@SleeplessByte Yup! https://github.com/exercism/javascript/pull/688

**Pull request merged**
