### PR TITLE
[new Exercise] lens-person 

### LINKED ISSUE #912: Add new exercise: lens-person
[problem specification ](https://github.com/exercism/problem-specifications/tree/master/exercises/lens-person)| [description](https://github.com/exercism/problem-specifications/blob/master/exercises/lens-person/description.md) | ~canonical data~

You may find it helpful to follow [this checklist](https://github.com/exercism/javascript/blob/83feda2af955df1ef9f3a8080338f506f0fdf696/CONTRIBUTING.md#new-exercise) from the [CONTRIBUTING.md](https://github.com/exercism/javascript/blob/83feda2af955df1ef9f3a8080338f506f0fdf696/CONTRIBUTING.md) resource. There is _not yet_ any canonical data at moment of creating this issue. You may come up with test cases yourself or (recommended) check tracks that have already implemented this exercise for inspiration.

### PR DESCRIPTION
**Pull request by sarava338**
created lens-person/ in exercises/practice
added .meta/config.json
added Instruction and Introduction in .docs/
added lens-person.js, lens.person.spec.js and .meta/proof.ci.js files
copied babel.config.js, LICENCE, .npmrc, .gitignore, .eslintrc
created src/ for util classes like Person.js, Name.js, Born.js, Address.js, Lens.js

I have checked test cases. But I am still not sure if tests are running fine, Please help me by checking the test cases especially test cases for **immutability**

### CODE REVIEW

**Comment by sarava338** [comment]
Hi Reviewers,

Need review.

**Comment by Cool-Katt** [comment]
@sarava338 
Is this still being worked on? 
As it is now, it doesn't pass the CI checks.

**Comment by sarava338** [comment]
> @sarava338 
Hi @Cool-Katt 

> Is this still being worked on? 
I could not able to solve this CI checks. And I have manually created all the files. But, I saw your commit msg in other new exercises that's being added to exercism, it's generated by **configlets**. I don't know how to do that as of now.

> As it is now, it doesn't pass the CI checks.


if you don't mind, Could you please take over this exercise. I am yet to learn more to create a new exercise on exercism...

**Comment by Cool-Katt** [comment]
@sarava338 

Okay then, with your permission, I'll file another PR.

About `configlet`, and other tooling we use, you can read more on the [docs page](https://exercism.org/docs/building/configlet/create). It may be useful to acquaint yourself with the docs and proper procedures for adding an exercise to the track.

**Comment by sarava338** [comment]
> @sarava338 
> 
> Okay then, with your permission, I'll file another PR.
> 
> About `configlet`, and other tooling we use, you can read more on the [docs page](https://exercism.org/docs/building/configlet/create). It may be useful to acquaint yourself with the docs and proper procedures for adding an exercise to the track.

@Cool-Katt Thanks Mate 🙂

**Pull request closed without merging**
