### PR TITLE
Fix #540 : Added more tests to nth-prime and altered example code

### LINKED ISSUE #540: Suggested improvements: Nth-Prime
I have a few questions/suggestions to improve the 'nth-prime' challenge. 

Should we make people use the [Prime Number Theorem](https://en.wikipedia.org/wiki/Prime_number_theorem)? Right now people can write a solution that just finds a preset amount of primes and then picks the nth prime (which is what the example does). This is obviously not an optimized approach as you will be waiting the same time to get the 1st prime as the 100th. Could this be solved by checking the time taken to find 100 primes is greater than that of 1 in a test?

If we were to add the test: 
```js
it('huge prime', function () {
    expect(prime.nth(18000)).toEqual(200183);
  });
```
then the example code would fail as not enough primes are generated. To me the example code isn't that robust and the tests allow for code that isn't robust as well.

Edit: I also thought that this currently allows the exact copying of the previous 'sieve' exercise, with a small addition of grabbing a single value from the array it gives. If this can be solved with almost no unique code then is it doing its job?

### PR DESCRIPTION
**Pull request by gavinhenderson**
The test execute time has gone from `2.975s` with the old example code and the old tests to `3.200s` with the new tests and the new example code.

### CODE REVIEW

**Comment by matthewmorgan** [comment]
@gavinhenderson looks great.  I took a similar approach with my solution a while back!

I appreciate the fact that you commented explaining the magical math.  It might be improved slightly by referring to a citation that explains the formula.  By way of example, here's that old solution I mentioned:

```javascript
import sieve from './sieve';  //my Sieve class from earlier

export default class Prime{

  // see http://en.wikipedia.org/wiki/Prime_number_theorem#Approximations_for_the_nth_prime_number
  nth(n) {
    if (n < 1) throw new Error("Prime is not possible");
    let approximateLimit = n * Math.log(n) + n * Math.log(Math.log(n));
    approximateLimit < 15 ? approximateLimit = 15 : {};
    return sieve(approximateLimit).primes[n - 1];
  }
}
```

Would you mind making that comment change?  Otherwise this PR looks good to me.

**Comment by gavinhenderson** [comment]
@matthewmorgan Thats the link added now

**Comment by matthewmorgan** [comment]
@gavinhenderson awesome-- thank you.

Can I ask you to squash your commits to one for this PR?  Please let me know if you need assistance with this, I'd be happy to help.

**Comment by gavinhenderson** [comment]
@matthewmorgan So I think I might have done it?

**Comment by matthewmorgan** [comment]
Nicely done.  Thanks for your contribution!

**Pull request merged**
