### PR TITLE
fix bowling exercise

### PR DESCRIPTION
**Pull request by danielj-jordan**
#399

### CODE REVIEW

**Comment by rchavarria** [comment]
What was the ESLint error? Nested ternary operators?

It can't be remove ternary operators, because there still are some.

@Radix16 do you think that some `function`s would make the code more readable? Don't be afraid to extract methods or variables if it makes the code better.

**Comment by Radix16** [comment]
Yes, you are correct.  The only linter error was the nested ternary ‘if’ operator.  I was reluctant to modify more code than necessary to address the linter error.   However given your direction, I will do more to clean up other code quality issues.

**Comment by Radix16** [comment]
@rchavarria I have taken another look at the current example for this exercise and compared it to the readme.md.   There seems to be a discrepancy between the two.  The readme.md clearly requires a roll(pins: int) function which is not present in the solution at all.  Instead the example uses a reduce method which a corresponding state structure to control the reduce.   

I can clean this up and make the example better fit the requirements as they are written or I can clean up the existing example by creating a function or two within the architecture of the current solution.  What is your preference?

**Comment by rchavarria** [comment]
I would prefer to have a right implementation of the exercise. Maybe, README and code are not in synch because other reasons. We should trust other sources. For example: for specs, we should check [canonical specs](https://github.com/exercism/problem-specifications/blob/master/exercises/bowling/canonical-data.json) for this exercise.

The same repo, has the [trusted version of the README](https://github.com/exercism/problem-specifications/blob/master/exercises/bowling/description.md).

First, I would check the README. Then, I would check canonical specs against current tests.

**Comment by danielj-jordan** [comment]
@rchavarria I have refactored the code.  However I do not believe the current example matches the canonical specs or the trusted version of the readme.   

The readme specifically states that a function should exist.  It does not exist in the sample.  The function is: roll(pins : int) .   Also there are a few tests that are not implemented in the spec.js file which are listed in the canonical specs.  One of which is listed here:
`"description": "bonus roll after a strike in the last frame cannot score more than 10 points",
    "property": "roll",
    "previous_rolls": [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10],
    "roll": 11,
    "expected": {"error": "Pin count exceeds pins on the lane"}`
I think this example and spec should be re-written to match the canonical version.   However I don't think it should be done within the scope for fixing the eslint errors.   Should I create an issue for this?

**Comment by rchavarria** [comment]
You're right. Let's create a new PR for matching canonical tests with tests on this track.

Feel free to create an issue and start working on it.

**Pull request merged**
