### PR TITLE
WIP Chore: integrity check without version, eslint per track and babel 7

### LINKED ISSUE #44: Configure ESLint to lint source code at development time
As discussed in [exercism/xjavascript#101](https://github.com/exercism/xjavascript/issues/101) and [exercism/xjavascript#26](https://github.com/exercism/xjavascript/issues/26), ESLint seems to be a good tool to lint JavaScript and ECMAScript source code.

Add it and configure it to lint source code at development time.

### LINKED ISSUE #502: Lint errors with line endings in windows
Hi everyone,

So I'm new with this project and when I try to run the lint command to solve some errors regarding #480, it shows errors about Expected linebreaks to be 'LF' but found 'CRLF'. I'm running this on windows. Should I change some configuration in the eslint for this?

### LINKED ISSUE #589: Suggestion: prefer eslint syntax over style
With [more](https://github.com/prettier/prettier) and [more](https://github.com/xojs/xo) tools becoming available to automatically format the code base to a certain set of style rules (and [more comprehensive](https://github.com/prettier/prettier-eslint/issues/101) than `eslint --fix`, I'm also more inclined to stop teaching style preference, as indicated by mentor notes, mentor guidance docs and discussions on slack.

## The current state
Currently, the javavscript `package.json` sets a _very restrictive_ code style (`airbnb`) and I *don't* think this:
- helps the student understand the language
- helps the student get fluent in a language
- helps the mentor mentoring as downloading exercises can result in wibbly wobblies all over the place

We don't instruct or enforce these rules (https://github.com/exercism/javascript/issues/44#issuecomment-416760562) strictly, but I seem them in mentoring comments and most IDE's will run these _automagically_ if present.

## Recommendation
I therefore recommend to drop down to [eslint:recommend](eslint:recommended"](https://eslint.org/docs/rules/)) or if we must have a non-company style guide, use [standard](https://github.com/standard/eslint-config-standard) with semicolon rules disabled (people should decide about ASI themselves -- I don't think pushing people who know about ASI helps anyone, and TS doesn't have them either).

If this is something we want, I think doing it sooner rather than later is good and will speed up #480 greatly. The eslintignore list is still quite long and I don't think tháts particularly helpful.

As a final note, I think we should _better_ communicate to the students to run `npm/yarn install` and then `npm/yarn test`. I also suggest running `test` followed by `lint` so that someone is only bugged once the test succeeds, instead of using a `"pretest": "lint"`:

```json
{ 
  "scripts": {
    "test": "test:jest && test:lint",
    "test:jest": "...",
    "test:lint": "..."
   }
}
```

### LINKED ISSUE #620: Checklist: drop eslint for exercises
Per #589,

- [x] move `eslint` config from root `package.json` into root `.eslintrc`
- [x] **remove** all `eslint` dependencies from exercise-level `package.json`
- [x] fix CI check to ignore eslint discrepancy between root and exercise-level `package.json` 
- [x] (optional): add script to add `eslint:recommended` to exercise-level `package.json` on "deploy".

### PR DESCRIPTION
**Pull request by SleeplessByte**
Closes #636 

This PR does a few things:
- add a bunch of `package.json` scripts so everything can be run on the `npm` + node context. Currently this track requires a _lot_ of setup on Windows to maintain or contribute to and some additional setup on certain versions of linux. This normalizes all the scripts and runs them in node.
- `npm run test:ci`
  - compare `package.json` but skip "version" (#628), and make sure only "track" scripts are available  (via json to string)
  - compare  `babel.config.json` (via string, instead of md5 -- no reason)
  - compare track `.eslintrc.json` with root `.eslintrc.track.json`  (via string, instead of md5 -- no reason)
  - lint all the exercises against `airbnb-base` by first calling `unsync:track`, followed `lint:track` and `sync:track`.
- `npm run sync:exercise exercise`
  - copy `babel.config.json` to exercise
  - copy `.eslintrc.track.json` to exercise (as `.eslintrc.json`)
  - _merge_ `package.json` from the root with the `exercize/package.json`, keeping `version` and `scripts`.
- removes duplication in the "lint-test" variant

Also fixes `QueenAttack` and `Octal`. We now need _way_ less babel plugin/transforms.

Additionally everything from #636 is still valid:

- Fixes #620, by adding track-only eslint
- Fixes #589, by adopting eslint:recommended for students (track-only)
- Fixes #502 (this is handled by git)
- Fixes #44 
- Workaround for maintainers on #421 by adding a script to copy the package.json to all exercises

I've done this as separate PR because if there are strong reasons to keep `Makefile`, we can just dump this. I rather have new maintainers and contributors only have to sift through `js` scripts tho, so I rather have all the make functionality in our language. I know how to do these things in `bash` but I don't see the point in increasing the cognitive complexity when we want to add something new (like the integrity check).

### CODE REVIEW

**Comment by SleeplessByte** [comment]
If this is approved; I'll write docs for it 📦

**Comment by tejasbubane** [comment]
I find it difficult to wrap my head around so many changes. Can we split these into small PRs and take it step-by-step please? Also the changes here look very similar to https://github.com/exercism/javascript/pull/636.

**Comment by SleeplessByte** [comment]
I don't think it's smart to split this up, except for the split with #636.

- We need the sync/unsync to run "lint" differently for maintainers / contributors vs students. We want `eslint:recommended` for them because it guards against syntax errors. This change does not make sense without also extracting `.eslintrc.json`.
- The non-makefile commands allow for better integrity checks which don't make sense as a change if we don't actually change the integrity check --- we also _want_ to check the integrity of the `package.json`.
- The babel change upgrades to babel 7 -- but that requires eslint changes. They go hand-in-hand and don't make sense to do separately.

If you have an idea how to split this up I'll do the work -- but I don't think it's wise.

The changes are the same as #636 and then more. This one "depends" on 636. That's the only split I made that was sane imo.

**Comment by tejasbubane** [comment]
> This one "depends" on 636.

Ok lets get #636 merged first then. Can you put this in WIP instead of 636?

**Pull request closed without merging**
