### PR TITLE
saddle-points: Fix row values in instructions

### PR DESCRIPTION
**Pull request by tejasbubane**
https://github.com/exercism/problem-specifications/pull/2272

### CODE REVIEW

**Review by junedev — COMMENTED** [review]
Could you please run a full "configlet sync"? There seem to be more changes than what is in this PR.

**Comment by tejasbubane** [comment]
> Could you please run a full "configlet sync"? There seem to be more changes than what is in this PR.

@junedev Done.

**Review by SleeplessByte — APPROVED** [review]

**Pull request merged**
