### PR TITLE
Rename conept exercise dirs: `closures` and `recursion`

### PR DESCRIPTION
**Pull request by angelikatyborska**
I noticed that there still are some concept exercises that are in directories named after concepts.

This PR renames:
- `closures` -> `coordinate-transformation`
- `recursion` -> `pizza-order`

There are 3 non-story directory names remaining, but I am not touching them:
- `array-loops` because it's already done in this draft PR https://github.com/exercism/javascript/pull/1097
- `errors` because it's not in the main `config.json` so it doesn't have a name. Should it be added there? is it waiting for improvements?
- `nullability` because it's deprecated

### CODE REVIEW

**Review by SleeplessByte — CHANGES_REQUESTED** [review]
We probably need to fix more in those exercises, so putting it on hold

**Comment by angelikatyborska** [comment]
In `recursion` yes, there's an issue: https://github.com/exercism/javascript/issues/945

`closures` looks pretty complete to me, except for the blurb.

Are you sure not merging this on its own is the best strategy? I'm not really volunteering to fix `recursion` so somebody would either need to branch off my branch or just redo the same changes. I don't really see any harm in merging just the dir renames.

**Comment by SleeplessByte** [comment]
It's a good indication currently on if it's old or not :p.

That's my only concern.

I can probably make time this weekend.

**Comment by SleeplessByte** [comment]
Narrator: I didn't

**Comment by junedev** [comment]
@angelikatyborska I discussed with @SleeplessByte that I will have look whether anything else needs to be fixed.

**Review by junedev — APPROVED** [review]
Discussed with @SleeplessByte that we put the recursion exercise back to "wip" for now because too many things are missing.

Added some more small fixes and the missing blurbs.

**Pull request merged**
