### PR TITLE
Improve Concept Exercise Poetry Door Club Policy (strings)

### LINKED ISSUE #1338: Improve Concept Exercise: Poetry Club Door Policy (strings)
The goal of this task is to make sure the Concept Exercise "Poetry Club Door Policy" and the Concept `strings` conform to the latest specification.

The docs can be found here

- [What are Concept Exercises?](https://exercism.org/docs/building/product/concept-exercises)
- [Concept Exercises](https://exercism.org/docs/building/tracks/concept-exercises)
- [Concepts](https://exercism.org/docs/building/tracks/concepts)

Additionally you can look at the code of an existing concept exercise like [`bird-watcher`](https://github.com/exercism/javascript/tree/main/exercises/concept/bird-watcher) (concept [`for-loops`](https://github.com/exercism/javascript/tree/main/concepts/for-loops)) for reference.

The improvement should include changing the introduction.md file of the exercise to contain some minimal information so that the student is able to solve the exercise. For now it is ok to use that same content as introduction.md and about.md for the Concept as well.

Also ensure that

- there are good blurbs for the concept and exercise
- the tests are declarative (see https://github.com/exercism/javascript/issues/1019 for an example)
- each test case is "self-contained" so that the student sees meaningful output from the test runner (no forEach, no helper functions defined in other parts of the test file etc.)

### PR DESCRIPTION
**Pull request by junedev**
Resolves #1338

### Changes
- Improve concept content
- Restructure test cases so they result in good output on the website (each test contains the needed variables)
- Restructure the introduction so information is given when needed instead of as a big block upfront
- Remove the capitalize helper function as suggested below
- Improve hints
- Remove the intermediate task (back door response without the trimming)
- Remove template strings from the introduction as they will be covered in the separate exercise and are not needed here

### CODE REVIEW

**Comment by iHiD** [comment]
Suggestion on this. Rename the `capitalize` method to `frontDoorPassword`

**Comment by junedev** [comment]
@iHiD Already on my cleanup list. 🙂

**Comment by DietCoke955** [comment]
Hi, im still having same issue as 1338  in this comment > 
> 
> From the editor bug reports:
> 
> > Error: expect(received).toBe(expected) // Object.is equality
> > Expected: "Horse, please"
> > Received: "E, please"
> > at BackDoorGuard.assert (/door-policy.spec.js:90:22)
> 
> > Can not concat. when i put .concat(`pleas`) my console log shows ''Horse pleas'' and if i put .concat(`please`) my console log shows only ''e''
> 
> > The arguments "responses" and "word" for the Test 11 (strings > back door > backDoorGuard(SHIRE_HORSE_WITH_SPACES)) is just the last letter of what the function backDoorResponse() is returning. For some reason, this is just happening for this test.
> > Example:
> > The function backDoorResponse() returns in each iteration "h", "o", "r", "s", "e", but the arguments "responses" and "word" feeding its respectives functions (backDoorPassword() and capitalize()) for the back door part of the exercise just constains "e". It should contain "horse".
> 
> > According to my observations, the last test of this challenge is wrong because when I return the argument in the function, it goes like this "     e" . It should have letters before that to solve that challenge, because even if I try to remove the whitespace I cannot fix it. Please help, I maybe mistaken.




However after the exercise was updated today it's just receiving an empty array instead and still failing. Any help? Thanks a bunch!

**Comment by junedev** [comment]
Please note that this is a draft PR (a work in progress). Its not yet available on the website therefore the issues in #1338 might still exist.  The only change that went live recently was a cleanup of the test code. But that by itself probably did not "fix" anything yet.

It would be great if you could post a code example how to reproduce your issue and see that empty array into #1338.

**Comment by pertrai1** [comment]
👍 LGTM

**Pull request merged**
