### PR TITLE
[lens-person] Remove `get` and `set` methods

### PR DESCRIPTION
**Pull request by themetar**
The methods were unused. [Discussion here](http://forum.exercism.org/t/possible-issue-in-unit-test-on-lens-person-exercise/12102/9)

### CODE REVIEW

**Review by Cool-Katt — APPROVED** [review]

**Comment by SleeplessByte** [comment]
@Cool-Katt I think you're supposed to have write-access. @ErikSchierboom do you know why they don't?

**Review by SleeplessByte — APPROVED** [review]
Thanks!

**Comment by Cool-Katt** [comment]
> @Cool-Katt I think you're supposed to have write-access. @ErikSchierboom do you know why they don't?

I thought so too, but I realized I never tried merging anything until now, so here we are. I think it's because the role that's given to exercism/javascript is triage so basically like write access but no merging of PRs, as I understood from the docs.

**Comment by SleeplessByte** [comment]
As far as I'm concerned you should get rights given the fact you accepted the maintainer position. Can you ping the peeps in your maintainer acceptance issue about this?

**Comment by iHiD** [comment]
> I think it's because the role that's given to exercism/javascript is triage

It was this. Fixed now.

**Pull request merged**
