### PR TITLE
Configure travis CI matrix

### PR DESCRIPTION
**Pull request by tejasbubane**
Test on multiple node versions to ensure nothing breaks for end-users.

### CODE REVIEW

**Comment by tejasbubane** [comment]
Our code fails on node [v6](https://travis-ci.org/exercism/javascript/jobs/548130402) and [v7](https://travis-ci.org/exercism/javascript/jobs/548130403). Relaxing the min node version to `v8`.

Anyways @SleeplessByte is of the opinion to support only latest LTS.

**Comment by SleeplessByte** [comment]
As long as we **COULD** support multiple versions, I'm all for it 💁; I do think we **SHOULD** only support latest LTS.

**Comment by tejasbubane** [comment]
I think this is fine to be merged now.

There was a mention of LTS in our [installation page](https://exercism.io/tracks/javascript/installation) before I feel. No able to find it now. I think we should add it. cc @SleeplessByte

**Comment by SleeplessByte** [comment]
@tejasbubane yes, let's get that (back) in.

**Comment by tejasbubane** [comment]
> But we might want to consider button v8 in `allow_failures`.

As of now the built succeeds. In future if we use some API unsupported by v8, we will consider moving it.

**Pull request merged**
