### PR TITLE
Add new exercise: book store

### LINKED ISSUE #733: Add new exercise: book-store
[problem specification][problem-specification] | [description][readme] |  [canonical data][canonical-data]

[problem-specification]: https://github.com/exercism/problem-specifications/tree/master/exercises/book-store
[readme]: https://github.com/exercism/problem-specifications/blob/master/exercises/book-store/description.md
[canonical-data]: https://github.com/exercism/problem-specifications/blob/master/exercises/book-store/canonical-data.json

### PR DESCRIPTION
**Pull request by mcampourcy**
Fixes #733

### CODE REVIEW

**Comment by SleeplessByte** [comment]
Great job so far! I think there is a bug in your `example.js`, given the failing tests :D

**Comment by mcampourcy** [comment]
Thanks !
Yep, looks like I missed something :sob:

**Comment by SleeplessByte** [comment]
Rebase on master to be able to run tests or prefix the command with `PREPARE=1`:

```
PREPARE=1 ASSIGNMENT=book-store npx @babel/node scripts/test
```

**Comment by mcampourcy** [comment]
> Rebase on master to be able to run tests or prefix the command with `PREPARE=1`:
> 
> ```
> PREPARE=1 ASSIGNMENT=book-store npx @babel/node scripts/test
> ```

It's working ! Thanks !

**Comment by mcampourcy** [comment]
@SleeplessByte I'm very sorry, but I'm struggling with that exercise :sweat_smile: 
The last test is taking forever to pass, and I guess it's because of the number of different combinations to test.
Could you help me with that one ?

**Comment by SleeplessByte** [comment]
> For simplicity, let us use the numbers 0 to 4 to represent the 5 books. A 5-tuple can represent the list of books. For example, the list `[0, 0, 1, 1, 2, 2, 3, 4]` can be represented by the 5-tuple `(2, 2, 2, 1, 1)`. The first element of the 5-tuple contains the number of occurrences of book 0, the second element contains the number of occurrences of book 1, and so on.
>
> The function price determines the minimum price for a given 5-tuple. For example, `price(1,0,0,0,0)` = `8` and `price(0, 1, 1, 0, 0)` = `15.2`.

> If the 5-tuple consists of only zeroes and ones, then the price can be determined by counting the number of ones. Multiply the number of ones by eight and apply the appropriate discount.

> A straightforward implementation will consume a lot of time: `price(2, 2, 2, 2, 2)` will evaluate `price(2, 2, 1, 1, 2)` two times and `price(2, 2, 0, 0, 2)` six times. By applying memoization this problem is solved: store the result for each 5-tuple once it has been evaluated. For the 5-tuple `(a,b,c,d,e)` the price function is evaluated at most `(a+1)*(b+1)*(c+1)*(d+1)*(e+1)` times.

**Comment by SleeplessByte** [comment]
Is it possible to tackle this?

**Comment by SleeplessByte** [comment]
Unfortunately the source repository has been deleted.

**Pull request closed without merging**
