### PR TITLE
Reverse string

### PR DESCRIPTION
**Pull request by eliaahadi**
updated folder

### CODE REVIEW

**Comment by matthewmorgan** [comment]
@eliaahadi thanks so much for your effort!  I need to figure out how best to approach this PR, because this exercise appears to be _entirely new_ to exercism.

I believe that the usual approach to adding a new exercise to exercism would be to open a request in the https://github.com/exercism/problem-specifications repo, and after that is merged, it can be implemented in specific languages.

@rchavarria can you comment on this?

I am also wondering if it is OK for us to implement an exercise attributed to an external author-- what permissions do we need @kytrinyx ?

Let's get these questions answered and then we can figure out the best way to proceed.

**Comment by eliaahadi** [comment]
Thanks good to know. Perhaps after we finally implement this, I can write step by step tutorial on how to do this from scratch to PR, it'd be helpful for me and others I'd think. The github PR I'm certainly still new at too.

**Comment by eliaahadi** [comment]
Hi I'm not exactly sure what's failing or perhaps you didn't have time to review this commit, any thoughts on how to move forward with this PR? Thank you.

**Comment by matthewmorgan** [comment]
@eliaahadi it looks like this and #417 are a PR for the same exercise.  Please see my comments there further explaining the process.

**Comment by eliaahadi** [comment]
this is a duplicate of #417

**Pull request closed without merging**
