### PR TITLE
Update instructions.md

### PR DESCRIPTION
**Pull request by npiyush97**
adding a note

### CODE REVIEW

**Comment by npiyush97** [comment]
@junedev

**Comment by SleeplessByte** [comment]
@npiyush97 you'll want to discuss this on the forum, or if that's already been done link the forum track so someone like junedev or me can take a quick look on the resolution there.

**Comment by npiyush97** [comment]
> @npiyush97 you'll want to discuss this on the forum, or if that's already been done link the forum track so someone like junedev or me can take a quick look on the resolution there.

no just want to contribute this that what it symbol is used to denote in js (**).
just clear out the confusion that's why added it as a note.
if you find this helpful then add this else can be as it is.

**Comment by SleeplessByte** [comment]
If you feel the instructions are confusing then further explanation is helpful, but we still ask everyone to follow [these instructions](https://github.com/exercism/javascript/pull/2383#issuecomment-1921028701).

**Pull request closed without merging**
