### PR TITLE
Update links in array introduction

### PR DESCRIPTION
**Pull request by raydancer**
I made some changes to the links in this introduction.  The basic links at the end weren't working for some reason, so I changed them to be more like the links in the Strings introduction.  I kept the MDN attributions at the end because the text was pulled directly from MDN reference site.

### CODE REVIEW

**Comment by junedev** [comment]
@raydancer Thanks for raising this but I have trouble reproducing the problem. All the places that you changed are quotes and the source for the quote is provided in the footnote. I tested the footnote and the link in the footnote on the website https://exercism.org/tracks/javascript/concepts/arrays and it all seems to work fine. :thinking: 

Could you clarify this:
> The basic links at the end weren't working for some reason

What happened when you went to the page linked there?

**Comment by raydancer** [comment]
You're correct, those links work when you go to the introduction page; however, the links don't work in the sidebar of the exercise editor: https://exercism.org/tracks/javascript/exercises/elyses-enchantments/edit

Is there something that breaks basic quotes when bringing them to the exercise sidebar?  If so, this might affect other introduction pages.

Also, I added inline code text markdown to unshift and splice to match the other sections.

**Comment by SleeplessByte** [comment]
@raydancer I think you mean that they are not linked here, right:

image

**Comment by raydancer** [comment]
Right.  The URL's are there, but they appear as text, not anchors.  I see that the link markdown was correct, but I don't understand why they didn't appear as links.

**Comment by SleeplessByte** [comment]
I think this may be something @ErikSchierboom would want to look at. I think what you're saying is: in one place of exercise, the links _are_ auto-linked, but in another place they are not. The solution would be to make them autolink on both places, or neither places.

**Comment by ErikSchierboom** [comment]
> I think this may be something @ErikSchierboom would want to look at. I think what you're saying is: in one place of exercise, the links are auto-linked, but in another place they are not. The solution would be to make them autolink on both places, or neither places.

@raydancer Could you create an issue at [exercism/exercism](https://github.com/exercism/exercism/issues) for this?

**Comment by raydancer** [comment]
> @raydancer Could you create an issue at [exercism/exercism](https://github.com/exercism/exercism/issues) for this?

Done:
https://github.com/exercism/exercism/issues/6522

**Comment by junedev** [comment]
I feel the better solution here is to wait for the Exercism-wide fix instead of merging this workaround. The links can still be copy and pasted and mainly exist only to provide the sources for the quotes. I am closing the PR.

**Pull request closed without merging**
