### PR TITLE
fix: removed unnecessary class from nucleotide count

### LINKED ISSUE #1473: Nucleotide Count: Remove unnessary class
The Nucleotide Count stub and exemplar solution currently contain a class definition that serves no purpose.
https://github.com/exercism/javascript/blob/0017b79c40521091794437fa0d0d9974de35c4d5/exercises/practice/nucleotide-count/nucleotide-count.js#L6-L7

The exercise should be changed so that the stub and exemplar only use a simple function definition, e.g.
```javascript
export function nucleotideCounts(strand) {
   // ...
}
```
The following files need to be updated:
* `nucleotide-count.js`
* `nucleotide-count.spec.js`
* `.meta/proof.ci.js`
* root level `config.json` (remove "classes" from the prerequisites of the exercise)

You can find general information about the structure of practice exercises here: https://exercism.org/docs/building/tracks/practice-exercises

### PR DESCRIPTION
**Pull request by lpizzinidev**
Closes #1473

### CODE REVIEW

**Review by SleeplessByte — APPROVED** [review]
Thanks, this looks great. Only request is to rename `nucleotideCounts` to `countNucleotides` or `parse` or something similar.

**Comment by SleeplessByte** [comment]
Oh, and don't forget to update `config.json` in the root (remove `classes`)

**Comment by lpizzinidev** [comment]
@SleeplessByte I've looked in the root `config.json` file but the `prerequisites` array for the exercise is already empty

**Comment by junedev** [comment]
@lpizzinidev @SleeplessByte The prerequisites for that exercise are not merged yet. I will leave a comment in the respective PR to remove them there.

**Review by junedev — APPROVED** [review]

**Pull request merged**
