### PR TITLE
twelve-days: use functions instead of class instance

### PR DESCRIPTION
**Pull request by cmccandless**

### CODE REVIEW

**Comment by SleeplessByte** [comment]
When I auto generate this, looking at [version 1.2.0](https://raw.githubusercontent.com/exercism/problem-specifications/master/exercises/twelve-days/canonical-data.json)

```
=> fetch spec from https://github.com/exercism/problem-specifications/raw/master
/exercises/twelve-days/canonical-data.json (10 redirections left)
=> fetch spec from https://raw.githubusercontent.com/exercism/problem-specificat
ions/master/exercises/twelve-days/canonical-data.json (9 redirections left)
=> generating twelve-days (1.2.0)

=> generating 2 cases for twelve-days

=> generating 12 cases for twelve-days -> verse
=> test twelve-days -> verse -> first day a partridge in a pear tree
=> test twelve-days -> verse -> second day two turtle doves
=> test twelve-days -> verse -> third day three french hens
=> test twelve-days -> verse -> fourth day four calling birds
=> test twelve-days -> verse -> fifth day five gold rings
=> test twelve-days -> verse -> sixth day six geese-a-laying
=> test twelve-days -> verse -> seventh day seven swans-a-swimming
=> test twelve-days -> verse -> eighth day eight maids-a-milking
=> test twelve-days -> verse -> ninth day nine ladies dancing
=> test twelve-days -> verse -> tenth day ten lords-a-leaping
=> test twelve-days -> verse -> eleventh day eleven pipers piping
=> test twelve-days -> verse -> twelfth day twelve drummers drumming

=> generating 3 cases for twelve-days -> lyrics
=> test twelve-days -> lyrics -> recites first three verses of the song
=> test twelve-days -> lyrics -> recites three verses from the middle of the song
=> test twelve-days -> lyrics -> recites the whole song
```

It seems like it only expects one exported property `recite`, but as you can tell from the naming here, there are two "outputs". I therefor understand your two outputs `verse, sing`, but perhaps this is the moment we have a single output:

`recite` (as in the canonical data) that _always returns a single string_?

**Comment by cmccandless** [comment]
> When I auto generate this

I wasn't aware there was a generator, or I would've used it.

As for your other comments: I merely took the test suite *as it already was* and removed the need for a class instance. I took no efforts to improve or update the tests. There are probably improvements that can/should be made, but those fall outside the scope of this PR.

**Comment by SleeplessByte** [comment]
> I wasn't aware there was a generator, or I would've used it.

I'm still writing it 😁  hehe.

> As for your other comments: I merely took the test suite as it already was and removed the need for a class instance. I took no efforts to improve or update the tests. There are probably improvements that can/should be made, but those fall outside the scope of this PR.

I don't agree. I don't want to burden students too often with changes to the exercise. I agree with the changes you've made sofar, but I prefer to sync it when we make changes like these. Does that make sense?

**Comment by cmccandless** [comment]
> Does that make sense?

Perfectly. I'll include those updates when I can.

**Comment by tejasbubane** [comment]
@cmccandless Hi, can you make those changes so that we can merge this in?

**Comment by cmccandless** [comment]
@tejasbubane Apologies; this slipped between the cracks. Changes pushed, just awaiting CI checks.

**Comment by cmccandless** [comment]
@tejasbubane Added, and I also synced the case names with the canonical data.

**Pull request merged**
