### PR TITLE
🤖 Add authors and contributors to Practice Exercises

### PR DESCRIPTION
**Pull request by ErikSchierboom**
**EDIT BY @SleeplessByte**: 👋🏽 this was merged. I did my best to make sure EVERYONE got their deserved credit. If you find that you didn't get it, please feel free to comment on this PR, or open a new issue and tag me directly. If you don't want that conversation to be public, feel free to grab my e-mail from my profile or reach me on slack.

---

_If you got tagged in this PR, it is because you are being credited for work you've done in the past on Exercism here, and we want to ensure you don't miss out on the recognition you deserve 🙂_

---

With v3, we've introduced the idea of exercise authors and contributors. This information is stored in the exercises' `.meta/config.json` files (see [the docs](https://github.com/exercism/docs/blob/main/building/tracks/practice-exercises.md#file-metaconfigjson)).

Concept Exercises, which are all new, already contain authors and contributors. Practice Exercises though are missing this information. In this PR, we attempt to populate the authors and contributors of Practice Exercises based on their commit history.

## Maintainer TODO list

These are the things you, the maintainers, should do:

- [x] Check the authors and contributors, adding/removing users where the data is missing or incorrect
- [x] Double-check any renamed Practice Exercises
- [x] Check for Practice Exercises with missing authors, which are most likely due to the author not being on GitHub anymore 
- [x] Add additional authors if you know that a Practice Exercise has actually been created by more than one author 

**For clarity, authors should be the people who originally created the exercise on this track. Contributors should be people who have substantially contributed to that exercise. PRs for typos or multiple-exercise PRs do not automatically mean someone should be considered a contributor to that exercise. Those non-exercise-specific contributions will get recognition through Exercism's reputation system in v3.**

If you find something needs updating, just push a new commit to this PR.

## Automatic Merging

We will automatically merge this PR before we launch v3, but will give the maximum time we can to maintainers to review it first.

---

_The rest of this issue explains how this PR has been generated. You do not **need** to read it._

## Algorithm

We start out by looking at the current Practice Exercises. For each Practice Exercise, we'll look at the commit history of its files to see which commits touched that Practice Exercise. How renames are handled is discussed in the "Renames" section later in this document. 

Any commit that we can associate with a Practice Exercise is used to determine authorship/contributorship. Here is how we assign authorship/contributorship:

### Authors

1. Find the Git commit author of the oldest commit linked to that Practice Exercise.
2. Find the GitHub username for the Git commit author of that commit
3. Add the GitHub username of the Git commit author to the `authors` key in the `.meta/config.json` file

### Contributors

1. Find the Git commit authors and any co-authors of all but the oldest commit linked to that Practice Exercise. If there is only one commit, there won't be any contributors.
1. Exclude the Git commit author and any co-authors of the oldest commit from the list of Git commit authors (an author is _not_ also a contributor) 
2. Find the GitHub usernames for the Git commit authors and any co-authors of those commits
3. Add the GitHub usernames of the Git commit authors and any co-authors to the `contributor` key in the `.meta/config.json` file

We're using the GitHub GraphQL API to find the username of a commit author and any co-authors. In some cases though, a username cannot be found for a commit (e.g. due to the user account no longer existing), in which case we'll skip the commit. 

## Renames

There are a small number of Practice Exercises that might have been renamed at some point. You can ask Git to "follow" a file over its renames using `git log --follow <file>`, which will also return commits made before renames. Unfortunately, Git does not store renames, it just stores the contents of the renamed files and tries to guess if a file was renamed by looking at its contents. This _can_ (and will) lead to false positives, where Git will think a file has been renamed whereas it hasn't. As we don't want to have incorrect authors/contributors for exercises, we're ignoring renames. The only exception to this are known exercise renames:

- `bracket-push` was renamed to `matching-brackets`
- `retree` was renamed to `satellite`
- `resistor-colors` was renamed to `resistor-color-duo`
- `kindergarden-garden` was renamed to `kindergarten-garden`

If you know of a rename of a Practice Exercise, please check to see if its authors and contributors are correctly set.

## Exclusions

There are some commits that we skip over, which thus don't influence the authors/contributors list:

- Commits authored by `dependabot[bot]`, `dependabot-preview[bot]` or `github-actions[bot]`
- Bulk update PRs made by `ErikSchierboom` or `kytrinx` to update the track

## Tracking

https://github.com/exercism/v3-launch/issues/24

---

cc @105ron, @AakashMallik, @abhnvgupta, @adamxtokyo, @alexashley, @amscotti, @andreasolund, @ankorGH, @apapirovski, @archanid, @arthurchipdean, @austinratcliff, @bdjnk, @BoDaly, @Boto1, @brendan-c, @brendanmckeown, @burennto, @chauchakching, @clockelliptic, @cmccandless, @cr0t, @d-vail, @DagmarTimmreck, @danielj-jordan, @daveyarwood, @designfrontier, @diego-caceres, @draalger, @drericrobinson, @ee7, @ErikSchierboom, @evelynstender, @felbit, @ffflorian, @Futuro212, @G-Rath, @gabriel376, @ganderzz, @gargrave, @gavinhenderson, @hayashi-ay, @hyuko21, @iagocavalcante, @iHiD, @IndelicateArgot, @ivanvotti, @javaeeeee, @jcshih, @JesseSingleton, @joeljuca, @joshgoebel, @jscheffner, @junedev, @komyg, @konni2020, @kytrinyx, @lantran, @laurmurclar, @LyleCharlesScott, @marocchino, @maruthimohan, @masters3d, @MattH-be, @matthewmorgan, @mgmatola, @mluisamc, @monte-hayward, @msomji, @nicholejeannine, @ntshcalleia, @OrthoDex, @ovidiu141, @PakkuDon, @paparomeo, @PatrickMcSweeny, @pawamoy, @petertseng, @PSalant726, @pyko, @ramadis, @ramitmittal, @rchavarria, @RobinCsl, @rpottsoh, @rsuttles58, @ryanplusplus, @saylerb, @Scientifica96, @seeksort, @serixscorpio, @skabbass1, @slaymance, @SleeplessByte, @smb26, @StevenACoffman, @tarunvelli, @tejasbubane, @tekerson, @thanhcng, @tikaro, @TomPradat, @trvrfrd, @Tyresius92, @Vankog, @WebCu, @whatcoda, @xarxziux, @yanick, @ZacharyRSmith, @zimmah as you are referenced in this PR

### CODE REVIEW

**Review by tejasbubane — DISMISSED** [review]

**Review by SleeplessByte — CHANGES_REQUESTED** [review]
I see a _lot_ of people listed who have not touched the exercise caused by the sync requirements. I will manually run over this ... when I have the time. Unless someone feels like doing it...

**Comment by SleeplessByte** [comment]
@ErikSchierboom can you remove this one from the auto-merge list? This will take some time to get right...

**Comment by iHiD** [comment]
@SleeplessByte If you can identify what went wrong, we can rerun the script (cc @SaschaMann to this as well as he commented on Slack but Slack seems to be broken atm). @ErikSchierboom You might like to see if you can see what happened here too.

**Comment by SleeplessByte** [comment]
Nothing went wrong persé. If this can be automatically fixed, that's great. I think what will remove 80% of the false positives is:

Ignore commits / files changing package.json (anywhere in the tree) and/or package-lock.json (anywhere in the tree). We later removed the lock files (from the exercise directories). The difficult part is that many of these commits will not be separated from actual changes. So you can't ignore _commits_, but most be checked on a file basis (instead of directory/*).

Almost _all_ changes to `package.json` and `package-lock.json` are insignificant so I would be okay with just ignoring them, if that were possible.

**Comment by SaschaMann** [comment]
> cc @SaschaMann to this as well as he commented on Slack but Slack seems to be broken atm

I deleted my Slack comment after I figured out the likely cause of the issue. Sorry if that caused any confusion! I checked the github history for a _directory_ but forgot that the files have since been moved to a different directory (`exercises/` to `exercises/practice/`). We'd recently pushed a co-authored commit to _all_ practice exercises which messed up the script.

Btw: I found it quite useful to have a branch with the final state of v2 when reviewing the PR (tag would work too). Makes it easier to skip to the right moment in time.

**Comment by SleeplessByte** [comment]
cc @joeljuca, @joshgoebel, @jscheffner, @junedev, @komyg, @konni2020, @kytrinyx, @lantran, @laurmurclar, @LyleCharlesScott, @marocchino, @maruthimohan, @masters3d, @MattH-be, @matthewmorgan, @mgmatola, @mluisamc, @monte-hayward, @msomji, @nicholejeannine, @ntshcalleia, @OrthoDex, @ovidiu141, @PakkuDon, @paparomeo, @PatrickMcSweeny, @pawamoy, @petertseng, @PSalant726, @pyko, @ramadis, @ramitmittal, @rchavarria, @RobinCsl, @rpottsoh, @rsuttles58, @ryanplusplus, @saylerb, @Scientifica96, @seeksort, @serixscorpio, @skabbass1, @slaymance, @SleeplessByte, @smb26, @StevenACoffman, @tarunvelli, @tejasbubane, @tekerson, @thanhcng

See first post. You're only tagged because you have contributed to this track in the past (YAY, thank you!) and we want to make sure everyone gets credit where credit is due.

**Comment by SleeplessByte** [comment]
cc @tikaro, @TomPradat, @trvrfrd, @Tyresius92, @Vankog, @WebCu, @whatcoda, @xarxziux, @yanick, @ZacharyRSmith, @zimmah.

See first post. You're only tagged because you have contributed to this track in the past (YAY, thank you!) and we want to make sure everyone gets credit where credit is due.

**Comment by ErikSchierboom** [comment]
> I see a lot of people listed who have not touched the exercise caused by the sync requirements. I will manually run over this ... when I have the time. Unless someone feels like doing it...

Do you have specific exercise/username examples?

**Comment by SleeplessByte** [comment]
Yes, but I don't know if this is what you need. 

Example: [`accumulate`](https://github.com/exercism/javascript/pull/1055#diff-3ad2a49195d51d60e1cafbbb869e10f8de0390b548a8c8e2a0308870db07403f)

```json
{
  "contributors": [
    "andreasolund",
    "ankorGH",
    "G-Rath",
    "gargrave",
    "iagocavalcante",
    "lantran",
    "paparomeo",
    "PSalant726",
    "rchavarria",
    "ryanplusplus",
    "SleeplessByte",
    "tejasbubane",
    "Tyresius92",
    "xarxziux"
  ],
}
```

Here is a list of people that, based on their contribution, should **not** have been listed. This list is **NOT** exhaustive. It's quite a bit of work to figure these out. What I did was take the commits that were _definitely_ not targeting accumulate (but automated syncs) and then take the contributors that didn't have a commit that _did_ target accumulate.

- `andreasolund`'s contribution: https://github.com/ErikSchierboom/javascript/commit/2229b6c5bb9dc4d4eea0d8889140fbadfb200b90#diff-a80ba28c8e984da2fd55bce2c4d699442fc1ef17a99d2743d5926780267ade58
- `G-Rath`'s contribution: https://github.com/ErikSchierboom/javascript/commit/ee98478ffd25f6ef381067a8e4e7dd074414cf8a#diff-a80ba28c8e984da2fd55bce2c4d699442fc1ef17a99d2743d5926780267ade58
- `gargrave`'s contribution: https://github.com/ErikSchierboom/javascript/commit/df7c876c0b3793f5169741e1c578db43fa880d10#diff-a80ba28c8e984da2fd55bce2c4d699442fc1ef17a99d2743d5926780267ade58
- `iagocavalcante`'s contribution: https://github.com/ErikSchierboom/javascript/commit/3bc0273a2494e95cd69734848a3710415acd9461#diff-a80ba28c8e984da2fd55bce2c4d699442fc1ef17a99d2743d5926780267ade58
- `lantran`'s contribution: https://github.com/ErikSchierboom/javascript/commit/67a7cd36ed43922d1dce5a5f200403298f50e546#diff-a80ba28c8e984da2fd55bce2c4d699442fc1ef17a99d2743d5926780267ade58
- `paparomeo`'s contribution: https://github.com/ErikSchierboom/javascript/commit/3d326baf1565c5d22e1b5f93ad5eabf2c0638e3a#diff-a80ba28c8e984da2fd55bce2c4d699442fc1ef17a99d2743d5926780267ade58
- `PSalant726`'s contribution: https://github.com/ErikSchierboom/javascript/commit/4e8f337fc0dc21d56fcf3b610e5548c74bdaf1a0#diff-a80ba28c8e984da2fd55bce2c4d699442fc1ef17a99d2743d5926780267ade58
- `rchavarria`'s contribution: https://github.com/ErikSchierboom/javascript/commit/2bae4e6d9928dc835686802fef2c450faf6c54ff#diff-a80ba28c8e984da2fd55bce2c4d699442fc1ef17a99d2743d5926780267ade58 + https://github.com/ErikSchierboom/javascript/commit/d97eb91586c9ff3ae3c43ec91097c90c56f92ef7#diff-a80ba28c8e984da2fd55bce2c4d699442fc1ef17a99d2743d5926780267ade58
- `ryanplusplus`'s contribution: https://github.com/ErikSchierboom/javascript/commit/d9be7e88af0bb61b926ffcc2ae1d0c29913222d1#diff-a80ba28c8e984da2fd55bce2c4d699442fc1ef17a99d2743d5926780267ade58 + https://github.com/ErikSchierboom/javascript/commit/9e7694edf076ad405abe8d24cbb5d0d6c0f751b3#diff-a80ba28c8e984da2fd55bce2c4d699442fc1ef17a99d2743d5926780267ade58 + https://github.com/ErikSchierboom/javascript/commit/2ecf4a45ba7f0948b3dd78b592267974278b1e2f#diff-a80ba28c8e984da2fd55bce2c4d699442fc1ef17a99d2743d5926780267ade58
- `Tyserius92`'s contribution: https://github.com/ErikSchierboom/javascript/commit/ee51e312c950b2a07448764c2313f8adaf3271b0#diff-a80ba28c8e984da2fd55bce2c4d699442fc1ef17a99d2743d5926780267ade58

This would literally leave:

- `ankorGH`, 
- `SleeplessByte`, 
- `tejasbubane`, 
- `xarxziux`

Tejas and I have definitely touched the exercises individually (almost always syncing the spec, changing the stub, or similar), `mathewmorgan` _is_ the author (or at least the person who added it to the repo). I have not checked `ankorGH` and `xarxziux`.

It's like this for every exercise. The only one I could find that was right was `square-root` and anything else added in the past few months.

**Comment by ErikSchierboom** [comment]
> Almost all changes to package.json and package-lock.json are insignificant so I would be okay with just ignoring them, if that were possible.

@SleeplessByte I'll work on this Tuesday. For me, it would be easiest if I could just re-generate the commits for this PR. I don't think you've yet pushed anything but the formatting, so would that be okay>

**Comment by SleeplessByte** [comment]
Yes. We've not done anything significant.

**Comment by SleeplessByte** [comment]
@ErikSchierboom should ALSO ignore exercise README.MD. We use hints.md

**Comment by joeljuca** [comment]
This work of rewarding contributors for their efforts is really awesome! It's been a while since I last contributed to something on Exercism, but it definitely makes me feel motivated to come back to it!

This community is awesome! ❤️

**Comment by ErikSchierboom** [comment]
To try and not make cross-wide exercise commits result in someone contributing to all exercises, I've just pushed a commit that does the following:

- Use the original algorithm to figure out which commits are linked to which exercises
- Filter the list of commits to only those commits that:
   1. Update less than 10 exercises or update less than the total number of exercises
- Use the filtered commits to determine the contributors

The main benefit of this algorithm is that there is no special handling of files, so I don't have to create a blacklist for the files that are not allowed. As such, the above algorithm also detects exercise-wide changes to files like `babel.config.js` or `.npmrc`.

Running the above algorithm resulted in [this commit](https://github.com/exercism/javascript/pull/1055/commits/d56fb9a02b8f36456211f886e993417d7ec3fbb6), which does indeed remove quite some contributors. Could someone check if the results look to be valid?

**Comment by Tyresius92** [comment]
Hey guys! Thanks so much for doing this! It's really nice to be recognized. 

I only really did a spot check for my name, but that commit does't look _quite_ right to me. I was the original implementor of the `dnd-character` exercise, but it looks like the linked commit has removed me as the author.

**Comment by ErikSchierboom** [comment]
@Tyresius92 Looking at that PR, the commit removed you due to your PR changing 112 files over many exercises, which I would not expect from adding a single exercise (if was a newline change). You should be re-added manually as an author.

**Comment by SleeplessByte** [comment]
@ErikSchierboom That's exactly what I meant with: it should exclude on a _file level_, not a _commit level_. Should I manually run through all the PRs fixing this?

**Comment by ErikSchierboom** [comment]
>That's exactly what I meant with: it should exclude on a file level, not a commit level. 

Good!

> Should I manually run through all the PRs fixing this?

Ehm, well maybe do some cross-checking?

**Comment by ErikSchierboom** [comment]
@SleeplessByte I could also give you a list of the commits that were excluded

**Comment by ErikSchierboom** [comment]
Aha, like that. Could you then provide the list of files? You mentioned package.json, package-lock.json and README.md, but it looks like there are more candidates, right?

**Comment by tejasbubane** [comment]
>  Could you then provide the list of files? You mentioned package.json, package-lock.json and README.md, but it looks like there are more candidates, right?

@ErikSchierboom Other than the ones you mentioned, we have `.eslintrc`, `.npmrc`, `babel.config.js`, `LICENSE`.

**Comment by SleeplessByte** [comment]
I will spot check

**Comment by SleeplessByte** [comment]
@matthewmorgan we're just going to give you too almost all the author credit ;)

**Comment by SleeplessByte** [comment]
@Tyresius92 we (Erik) fixed it!

image

**Review by SleeplessByte — APPROVED** [review]

**Comment by Tyresius92** [comment]
> @Tyresius92 we (Erik) fixed it!
> 
> image

Thanks!

**Pull request merged**
