### PR TITLE
Issue1013:  CI should check if repository value of package.json is sane

### PR DESCRIPTION
**Pull request by AbhilashJN**
- Added script `scripts/directory-check` to check if `directory` field in the package.json for each exercise is correct.
 - Added documentation in CONTRIBUTING.md for `directory-check` script
 - Run `directory-check` script from `ci-check` and `pr-check` scripts in the integrity check step.
 
Ref Issue: #1013

### CODE REVIEW

**Comment by AbhilashJN** [comment]
The referenced also mentions that
```
Instead, the package.json in the exercise directory should:

match type of the root package.json repository
match url of the root package.json repository
```

However, it seems to me that the `type` and `url` fields are already being checked as part of the checksum, so I am not sure if anything else needs to be done for this. Do let me know if I have misunderstood this part.

**Comment by SleeplessByte** [comment]
Are we certain it's being checked as part of the checksum? It seems that if each `concept/***/slug` directory contains a `package.json` with a _different_ value for `repository.url`, it likely is **not** part of the checksum (nor should it), because it would be different 👍🏽

**Comment by AbhilashJN** [comment]
Currently it looks like for all the exercises, the `repository.url` field has the value `https://github.com/exercism/javascript`. Is it supposed to be different for each exercise, perhaps something like `https://github.com/exercism/javascript/exercises/<exercise-path>` ?

**Comment by SleeplessByte** [comment]
From the references issue:

```
Instead, the package.json in the exercise directory should:

match type of the root package.json repository
match url of the root package.json repository
have the correct directory based on the path to the exercise
```

So the url should be the same, the type should be the same, but the `directory` should be set.

**Comment by AbhilashJN** [comment]
In that case, it looks like no further changes are required. The type and url are being compared to the root package.json as a part of the checksum.

**Pull request merged**
