### PR TITLE
bracket-push: rename to matching-brackets

### PR DESCRIPTION
**Pull request by SleeplessByte**
This rename was proposed in:
exercism/problem-specifications#1501

The rationale for the name is:

* to name the exercise by its story, not by what it potentially teaches
* to avoid unnecessarily biasing the solution space

### CODE REVIEW

**Comment by tejasbubane** [comment]
Is it ok to merge this before the problem-spec PR is merged?

**Comment by SleeplessByte** [comment]
@tejasbubane 

These two have already been merged so I expect it's fine!
https://github.com/exercism/ceylon/pull/88
https://github.com/exercism/haskell/pull/819

**Comment by tejasbubane** [comment]
Yes, I saw the haskell PR. But this comment made me think again: https://github.com/exercism/problem-specifications/issues/1495#issuecomment-481057849

**Comment by tejasbubane** [comment]
I suggest holding off until problem-spec is updated - just as a precaution for issues like ones with `resistor-colors`.

**Comment by SleeplessByte** [comment]
FWIW https://github.com/exercism/csharp/pull/1276 did get merged. I agree with holding-off; let's see what happens with that :)

**Comment by SleeplessByte** [comment]
https://github.com/exercism/problem-specifications/pull/1501 got merged.

**Pull request merged**
