### PR TITLE
Use non-interpolating string delimiters

### PR DESCRIPTION
**Pull request by habere-et-dispertire**
--
🤝 https://forum.exercism.org/t/poetry-club-door-policy-template-string-delimiters/7175

### CODE REVIEW

**Comment by SleeplessByte** [comment]
@habere-et-dispertire we use single quotes in this repo per the `prettier` configuration!

**Comment by habere-et-dispertire** [comment]
Oh, okay. When I ran it through prettier.io it seemed to suggest the opposite.

**Comment by SleeplessByte** [comment]
https://github.com/exercism/javascript/blob/main/.prettierrc#L3 this is why ;)

**Review by SleeplessByte — APPROVED** [review]

**Pull request merged**
