### PR TITLE
Bob approaches prettierfied

### PR DESCRIPTION
**Pull request by bobahop**

### CODE REVIEW

**Comment by bobahop** [comment]
C'mon,

/format

please.

**Comment by SleeplessByte** [comment]
It formatted! 

[`b210689` (#2018)](https://github.com/exercism/javascript/pull/2018/commits/b210689d69c95544670cb9839c33ad7f424e22df)

**Comment by bobahop** [comment]
@SleeplessByte: Okay! So can this  be merged now?

**Review by tejasbubane — APPROVED** [review]

**Pull request merged**
