### PR TITLE
Port connect exercise from ECMAScript track

### PR DESCRIPTION
**Pull request by AdhirRamjiawan**
@rchavarria @matthewmorgan Implemented the following to resolve issue #389. Please let me know if all is well.

### CODE REVIEW

**Comment by rchavarria** [comment]
@AdhirRamjiawan - 😞 there are some tests for the exercise that are failing, could you review them, please?

**Comment by rchavarria** [comment]
I edited the title of the PR to make it clear that it's about porting an exercise. I find it more human readable than the issue number in the title.

@AdhirRamjiawan - any news on this?

**Comment by AdhirRamjiawan** [comment]
Hi @rchavarria , apologies for not getting back sooner! I've been having issues running the tests properly on my local machine. I'm using Windows. I've even tried setting up cygwin to run the Makefile to test however it doesn't run any of the tests.

**Comment by rchavarria** [comment]
Ok, it seems really difficult to run all tests in a Windows machine. First, you shoule have the `make` tool, but then you'd need some Linux-like tools, such as `sed`. So, I'm not sure it's worth the effort.

So, let's try to fix the build without using those tools. Looking at the Travis console output, it seems your implementation of the exercise can't make all tests to pass.

First, let's try to run those tests locally. Then, we'll fix the broken tests. To run them, se need to do some manual changes that are automatically done by Travis:

1. I assume you install `jasmine` tool globally with `npm -g install jasmine` ([installing instructions](https://github.com/exercism/javascript/blob/master/docs/INSTALLATION.md#installing-additional-tools))
2. In the command line, move to the exercise folder: `cd exercises/connect`
3. Modify first line in `connect.spec.js` to require the right file `var Board = require('./example');` (*it will need to be reverted to run tests on Travis*)
4. Find `xit` and replace them with `it`. We're enabling all test specs (*it'll also need to be reverted)
5. Run all tests with `jasmine connect.spec.js`

You should see a bunch of test information, what tests are passing and what are failing. Could you put here what you get?

**Comment by tejasbubane** [comment]
@AdhirRamjiawan Did you figure this one out? We would really like this one completed and merged.

**Comment by AdhirRamjiawan** [comment]
Hi @tejasbuban, I'm really sorry in delaying the response for this. I'm really struggling to get this one to work. Just wondering if someone else can have a look at it?

**Comment by matthewmorgan** [comment]
@tejasbubane @AdhirRamjiawan I'm happy to help with this.  I'll take a look at it.

**Comment by matthewmorgan** [comment]
Closing in favor of #461

**Pull request closed without merging**
