### PR TITLE
add exercise version to package.json based on canonical-data.json

### LINKED ISSUE #628: Create exercise versioning policy based on Haskell track
Exercism tracking issue: https://github.com/exercism/exercism/issues/4786
- haskell: https://github.com/exercism/haskell/pull/717/files#diff-c6795c529069232683d979cd4239c219R2
- ocaml: https://github.com/exercism/ocaml/issues/283
- javascript: https://github.com/exercism/javascript/issues/628

**Note**: This is not the same as https://github.com/exercism/exercism/issues/4266 which removed tracking versions from the user code.

## Proposed implementation for JavaScript

In `package.json` change the `version` number to match the `x.y.z` of [test data versioning](https://github.com/exercism/problem-specifications#test-data-versioning), and add `.q` which we always increment if a change is made without a sync (new test data): `x.y.z.q`.

### PR DESCRIPTION
**Pull request by gabriel376**
closes #628 

I have updated all exercises package.json to have its version field matching canonical-data.json version (when available)

I am a lazy developer, so I used the following bash script:
```
#!/bin/bash

version=`curl -s https://raw.githubusercontent.com/exercism/problem-specifications/master/exercises/$1/$
version="${version:0:6}.0\""

if [[ ${#version} == 3 ]]; then
    echo "error while getting version from canonical-data.json"
    exit 1
fi

echo "setting $1 to version $version"
file="../src/javascript/exercises/$1/package.json"
jq ".version = $version" "$file" | sponge "$file"
```

Usage:
```
sudo apt-get install jq moreutils
bash script.sh <exercise-name>
```

Notes:
1) I can remove the last version number .q if necessary (from 1.0.0.0 to 1.0.0)
2) We need to update others fields of package.json, like name, description, author, repository etc

### CODE REVIEW

**Comment by gabriel376** [comment]
build failed, I guess we need to remove `make test-travis` on Travis that checks if exercise package.json matches main package.json

**Comment by tejasbubane** [comment]
>  I guess we need to remove `make test-travis` on Travis that checks if exercise package.json matches main package.json

Thats right. We will have to remove/change it.

**Comment by tejasbubane** [comment]
@gabriel376 The issue here is not all exercises are synced with problem specifications. Some (if not most) lag behind and miss some tests or have old version of tests. We need to take this case by case basis and do the following:

* If all tests match, just update version number and we should be good.
* If tests don't match, make the changes required to match them and then update the version number.

This is what will make the version numbers useful - keeping tests in sync. Sorry I should have been more clear about this in the issue description.

**Comment by gabriel376** [comment]
> @gabriel376 The issue here is not all exercises in this track are in sync with problem specifications. Some (if not most) lag behind and miss some tests or have old version of tests. We need to take this case by case basis and do the following:
> 
> * If all tests match, just update version number and we should be good.
> * If tests don't match, make the changes required to match them and then update the version number.
> 
> This is what will make the version numbers useful - keeping tests in sync. Sorry I should have been more clear about this in the issue description.

Yes, it was not clear to me based on description of #628, sorry about that.
I suggest to open individual issues/PRs for each exercise sync, like other tracks do (see [this](https://github.com/exercism/python/issues/1677))
I can help in some of them.

**Comment by tejasbubane** [comment]
> I suggest to open individual issues/PRs for each exercise sync, like other tracks do (see [this](https://github.com/exercism/python/issues/1677))
> I can help in some of them.

Yes I just realized that and [commented on the issue](https://github.com/exercism/javascript/issues/628#issuecomment-469569417). Please go ahead and make separate PRs. You can combine a few (not more than 3 or 4) exercises together if you wish.

**Comment by gabriel376** [comment]
No problem =)
Thank you!

**Comment by SleeplessByte** [comment]
@gabriel376 thank you for the initial work tho ❤️

**Pull request closed without merging**
