### PR TITLE
added test case 'can handle messages longer than the key'

### PR DESCRIPTION
**Pull request by Vankog**
I just saw an exercise implementation of somebody who did not account for messages longer than the key and I figured this needs to be in the spec.

### CODE REVIEW

**Comment by matthewmorgan** [comment]
Capital idea!  We just accepted a PR to the ecmascript track for a similar test.  Although the `example.js` in that track handles these cases correctly, there was no test there either.  You might [take a look](https://github.com/exercism/ecmascript/pull/347) if you're curious.

Thanks for your contribution!

**Comment by Vankog** [comment]
@matthewmorgan: Github does this automatically if you enable it in the merge settings of your repository:
[https://github.com/blog/2141-squash-your-commits](https://github.com/blog/2141-squash-your-commits)
[https://help.github.com/articles/about-pull-request-merges/](https://help.github.com/articles/about-pull-request-merges/)
You can even enforce "squash only". 
So you don't have to wait for contributors to squash their commits themself. ;-)

(I have no local setup right now for my branch, that's why I'm telling you.)

**Comment by matthewmorgan** [comment]
@Vankog I'm aware of that, thank you.  We ask contributors to do it because for many of them, knowing _how_ to do so locally is a useful skill, and many have not learned how.

If squashing locally is old hat to you, I can do it during the merge.

**Comment by Vankog** [comment]
Ah I see, being pedagogical. Now I remember this repo being showcased on the github homepage as newbie friendly. Now I see why. :-)

OK then, I use TortoiseGit anyways. So it was just a matter of selecting the commits and hitting squash.

**Comment by matthewmorgan** [comment]
Indeed :) teaching is part of the goal!

Thanks for your contribution.

**Pull request merged**
