### PR TITLE
add .gitignore to all exercises

### PR DESCRIPTION
**Pull request by Bernardoow**
## What

- Add a .gitignore file to exercises.
- Add .gitignore to sync scripts ( This changes going to copy .gitignore to every exercises)
- Add .gitignore to checksum scripts ( This changes going to compare .gitignore on each exercises with the .gitignore root.)

## Why

I looked at other exercises and all of them have the .gitignore file. It prevents tracking  node_modules.

### CODE REVIEW

**Comment by Bernardoow** [comment]
Hi @SleeplessByte 

I just checked all concept exercises. And just this exercise is missing the .gitignore.

The others I have not checked yet. A few moments ago, after I opened this PR I found two-fer on the same situation. I going to check every exercise now.

**Comment by Bernardoow** [comment]
I checked the practice exercises and they do not have any.  Just concept exercises have the gitignore. 

Is it a better option the exercises don't have the gitignore? On 'my flow', I'm downloading the exercises and saving the response to my private repo. Now I need to copy and paste the gitignore file. Maybe in the future, if it is the best choice, I can put the gitignore on all exercises.

**Comment by SleeplessByte** [comment]
@Bernardoow I like it if we have .gitignore for all exercises. Would be nice if we had it everywhere!

**Comment by Bernardoow** [comment]
Hey guys !!

Ok @SleeplessByte!! 

@tejasbubane  Thanks for the tip !! I'm going to do this today !!

**Review by tejasbubane — APPROVED** [review]

**Review by SleeplessByte — APPROVED** [review]
Looks good. Thanks!

**Pull request merged**
