### PR TITLE
Issue 1019: Improve Annalyn's infiltration by making the tests declarative

### PR DESCRIPTION
**Pull request by AbhilashJN**

### CODE REVIEW

**Review by SleeplessByte — APPROVED** [review]

**Comment by SleeplessByte** [comment]
Could you please add a space between the `=`s and variable names, and values, so it's consistent with the rest?

```diff
- const foo=true
+ const foo = true
```

**Comment by AbhilashJN** [comment]
I have updated the PR

**Comment by SleeplessByte** [comment]
Thank you @AbhilashJN !!

**Pull request merged**
