### PR TITLE
Avoid mutations on List#toArray() (simple-linked-list exercise)

### PR DESCRIPTION
**Pull request by joelwallis**
@tejasbubane caught this on exercism/ecmascript#345, while reviewing @apapirovski's ECMAScript version of this exercise

### CODE REVIEW

**Comment by joelwallis** [comment]
Wow, 400th PR! 😲

**Comment by joelwallis** [comment]
I added expectations to the `List#toArray()` test case, but I think it hurts the isolation of the test case itself. Maybe it would be better to create a separated test case for this scenario. Does it make sense or I'm just byte brushing here?

**Comment by tejasbubane** [comment]
> but I think it hurts the isolation of the test case itself. Maybe it would be better to create a separated test case for this scenario. Does it make sense or I'm just byte brushing here?

We already have multiple `expect`s in a single test example, so I guess its fine.

**Comment by matthewmorgan** [comment]
I agree with @tejasbubane. Especially because those "multi-expect" tests are working together to test the behavior that the test describes.

Thanks @joelwallis !

**Pull request merged**
