### PR TITLE
OCR convert to function

### PR DESCRIPTION
**Pull request by xarxziux**
As discussed in issue #563, this is s full rewrite of the OCR exercise, ditching the class design of the original.

### CODE REVIEW

**Comment by SleeplessByte** [comment]
Hi there @xarxziux, 

Thank you for this work. Would you be so kind to update this to the latest master (and resolve the conflicts)? We'll be happy to review (and merge) it soon thereafter.

**Comment by xarxziux** [comment]
OK, it took me a little while to figure out what I was doing here, but I think I have it now!

**Comment by tejasbubane** [comment]
For the record, this is done because all methods in [the Parser class were static]( https://github.com/exercism/javascript/blob/9c009439465975142db21dd62d3185916174348f/exercises/ocr-numbers/example.js) - so it did not make much sense to keep class.

**Comment by SleeplessByte** [comment]
(sidenote: @tejasbubane do we run example.js on CI to make sure there is a working implementation?)

**Comment by tejasbubane** [comment]
> do we run example.js on CI to make sure there is a working implementation? 

Yes we run the test cases against examples. This Makefile does all the heavy lifting: [ref](https://github.com/exercism/javascript/blob/master/Makefile#L25)

**Pull request merged**
