### PR TITLE
add named export to palindrome products

### PR DESCRIPTION
**Pull request by smb26**
see issue #600

### CODE REVIEW

**Comment by SleeplessByte** [comment]
I prefer `generatePalindromes` or simply `palindromes` (or `palindromeProducts`) over `generate`, to be consistent with the other exercises.

**Comment by smb26** [comment]
strange, I could swear I added the pull request this morning with the name already changed

**Comment by smb26** [comment]
Actually, it is already the requested name (generatePalindrome)

**Comment by smb26** [comment]
Or is it the request change related to the s (now that I noticed that I used generatePalindrome instead of generatePalindromes)

**Comment by smb26** [comment]
That's awesome, thank you guys for the opportunity :)

**Pull request merged**
