### PR TITLE
Possible simplification of Translation Service exemplar

### PR DESCRIPTION
**Pull request by mmmmmrob**
By using `.catch()` and by wrapping `this.api.request()` as a promise some of the logic can be simplified.

Also suggest removing the `.bind(this)` as complex at this stage of the learning.

### CODE REVIEW

**Review by SleeplessByte — APPROVED** [review]
Thanks. Great changes!

**Comment by mmmmmrob** [comment]
Fixed the failing linter check for shadowing variables in inner functions.

**Comment by mmmmmrob** [comment]
@SleeplessByte What's the next step for this? I'm happy to do whatever the next step is if that's helpful?

**Comment by SleeplessByte** [comment]
Me pressing merge

**Pull request merged**
