### PR TITLE
(circular-buffer) Update example.js

### PR DESCRIPTION
**Pull request by TomPradat**

### CODE REVIEW

**Comment by TomPradat** [comment]
I didn't get how to test in local though. I installed the dependencies with `npm install` and tried `ASSIGNMENT=circular-buffer npx @babel/node scripts/test`. I also tried the sync command

**Comment by SleeplessByte** [comment]
The test also needs to be updated to use `new CircularBuffer`, or you need to add a "wrapper" factory function. Replace `export default class` with `class` and add `export default (...params) => new CircularBuffer(...params)`

What is the issue with the scripts?

**Comment by TomPradat** [comment]
Yeah i see what you mean. The test outputs `No tests found`. I guess I'm not using the command right...

**Comment by mcampourcy** [comment]
@SleeplessByte @TomPradat I've had the same problem ! I launched the tests with the `npm run test` commans directly in my exercise folder

**Comment by TomPradat** [comment]
> 
> 
> @SleeplessByte @TomPradat I've had the same problem ! I launched the tests with the `npm run test` commans directly in my exercise folder

This runs the test against the stub file not the example

**Comment by SleeplessByte** [comment]
Are you running `ASSIGNMENT=circular-buffer npx @babel/node scripts/test` from the _root_ folder of this repo?

What OS are you on and which terminal are you using?

**Comment by TomPradat** [comment]
So yeah i've tried to run this from the root folder. I got the same problem on WSL and on macOS

**Comment by SleeplessByte** [comment]
@TomPradat rebase on master, OR prepend your script with `PREPARE=1`:

```
PREPARE=1 ASSIGNMENT=circular-buffer npx @babel/node scripts/test
```

**Pull request merged**
