### PR TITLE
Format track config with `configlet fmt`

### PR DESCRIPTION
**Pull request by BNAndras**
The configlet CI is currently failing because `configlet fmt` is showing the track config to be unformatted. This is a recently added check for configlet.

### CODE REVIEW

**Comment by BNAndras** [comment]
Right, if I run `./bin/format.sh`, we go back to the original formatting that `configlet fmt` doesn't like.  `configlet fmt` should format the config.json files so maybe prettier shouldn't format those JSON files. That'll let us make both CI checks happy.

**Comment by SleeplessByte** [comment]
If we want to format it using configlet, we should probably:

- ignore the file using [`.prettierignore`](https://prettier.io/docs/en/ignore.html#ignoring-files-prettierignore)
- update `format.sh` to call both `prettier` and `configlet`.

I would be happy to see that change!

**Comment by BNAndras** [comment]
I’ll take a look. configlet create now formats the track config as well so that this issue is likely to come up again.

**Comment by SleeplessByte** [comment]
Understood! Ping me when done or if you cannot figure it out and I'll fix it ;)

**Comment by BNAndras** [comment]
Last commit was because raindrops has an exercism/note section in the instructions.md. Prettier wanted to revert the tildes to backticks.

**Comment by BNAndras** [comment]
@SleeplessByte, the CI is passing.

**Review by SleeplessByte — APPROVED** [review]

**Pull request merged**
