### PR TITLE
dibs: I will implement the simple-linked-list exercise

### PR DESCRIPTION
**Pull request by javaeeeee**
dibs: I will implement the simple-linked-list exercise

### CODE REVIEW

**Comment by rchavarria** [comment]
That would be awesome, to have yet another new exercise.

I see that `simple-linked-list.spec.js` and `example.js` files have no content yet in the PR. I think this is a work in progress PR, so I think @javaeeeee will implement them.

Also, due to some recent merges, there is a conflict on `config.json` (two exercises have been added at the end of the list of exercises). Please, @javaeeeee, be careful with this.

Ideally, the PR branch should be rebased with the latest changes in xjavascript/master. So, it'd involve update your fork with xjavascript changes. Then rebasing your own branch, and then update this PR by pushing that branch. This is all git jargon, so feel free to ask for help if you need some.

**Comment by javaeeeee** [comment]
Thank you.

**Comment by matthewmorgan** [comment]
@javaeeeee Hi Dmitry, 

Are you able to resolve this merge conflict?  I'm happy to help, or do it for you if you are busy-- let's get your work to the people!

**Comment by javaeeeee** [comment]
Just a moment, please.

**Comment by javaeeeee** [comment]
@matthewmorgan Hello, Matthew,

Done. Going to finish this piece this week.

**Comment by matthewmorgan** [comment]
👍

**Comment by joelwallis** [comment]
@matthewmorgan Hi. Did you have a chance to review this PR? It's pending for 5 months now, it's time to get it done - or close it if for some reason it became irrelevant.

**Comment by joelwallis** [comment]
Lemme know if you need some more work on this. We could ping @javaeeeee or I can continue his work if he's not available.

**Comment by tejasbubane** [comment]
@joelwallis Lets wait for a week, if @javaeeeee does not turn up, you can pick this up.

**Comment by joelwallis** [comment]
@tejasbubane roger that!

**Comment by tejasbubane** [comment]
@joelwallis Its been a while, looks like @javaeeeee hasn't turned up. I think you can go ahead and finish this one.

**Comment by matthewmorgan** [comment]
@joelwallis are you planning on bringing this one home?  Let me know if I can help....

**Comment by joelwallis** [comment]
@matthewmorgan I am! Sorry for taking so long. I'm prioritizing this PR now.

**Comment by matthewmorgan** [comment]
@joelwallis no apology necessary!  I was just doing a little housekeeping over the weekend :)

**Comment by joelwallis** [comment]
I'm closing this PR. The Simple Linked List was implemented in #372.

**Pull request closed without merging**
