### PR TITLE
Make configlet lint pass all checks

### PR DESCRIPTION
**Pull request by tejasbubane**
Related https://github.com/exercism/javascript/issues/961

1. Add solution and spec files for `elyses-transformative-enchantments` exercise.
2. Fix all other minor configlet lint issues.

### CODE REVIEW

**Comment by tejasbubane** [comment]
Looks like the CI scripts need to be fixed for new v3 directory structure (`exercises/concept`, `exercises/practice`).

**Comment by SleeplessByte** [comment]
@tejasbubane yes, when you're add it, `example.js` in practice exercises should move to `.meta/proof.ci.js`. `example.js` in concept exercises should become `.meta/exemplar.js` (not example.js).

I can make this change if you fix the CI, or you can do it in one go 🗡️

**Comment by ee7** [comment]
Just a side note: you might prefer for this PR to not close #961.

That issue doesn't mention it, but `configlet lint` currently only implements a small subset of the final linting rules. The track state as of this PR will probably not pass all `configlet lint` checks as `configlet` is updated in the future. 

See [this PR's configlet run in the log](https://github.com/exercism/javascript/runs/1841796690#step:4:7) for what is currently checked - it is only a subset of [the eventual linting rules](https://github.com/exercism/docs/blob/main/anatomy/tracks/configlet/linting.md).

Ping @ErikSchierboom - should we update the wording of each track's "[v3] Pass linting checks" issue, and suggest that maintainers keep them open for the near future?

(I haven't reviewed this PR).

**Comment by ErikSchierboom** [comment]
@ee7 That might be a good idea.

**Comment by ErikSchierboom** [comment]
@ee7 All the issues have been updated.

**Comment by SleeplessByte** [comment]
I have an hour right now, so I'm checking out your branch and seeing if I can resolve this.

**Comment by SleeplessByte** [comment]
Superseeded by #997

**Pull request closed without merging**
