### PR TITLE
Add stub files for exercises

### PR DESCRIPTION
**Pull request by ankorGH**
Inspired from #679 

Add stub files to all exercises within the difficulty 1 - 6.

cc @tejasbubane

### CODE REVIEW

**Comment by SleeplessByte** [comment]
This is amazing @ankorGH ! Thank you very much.

Personally, and this is not your fault, I'm not a fan of the repeated `// your code goes here` blocks, which I think is really only necessary for the first (`two-fer`) exercise, and is especially ugly when it's multiple times in a file:

```javascript
class Allergies {
  constructor() {
    //
    // YOUR CODE GOES HERE
    //
  }

  list() {
    //
    // YOUR CODE GOES HERE
    //
  }

  allergicTo() {
    //
    // YOUR CODE GOES HERE
    //
  }
}
```

vs

```javascript
class Allergies {
  constructor() {

  }

  list() {

  }

  allergicTo() {

  }
}
```

Perhaps we'd like to `throw` a not implemented exception instead. (We should check Java and C# stubs, see if they have that or no).

```javascript
export class Allergies {
  list() {
    throw new Error('Not implemented. Implement this method and remove this error.')
  }
 // etc.
}
```

**Comment by tejasbubane** [comment]
This is partly my bad for pasting existing `hello-world` stub in the issue description, modified for `two-fer` without giving much thought. Now that I think of it, I agree with all suggestions made by @SleeplessByte. 👍 

[java](https://github.com/exercism/java/blob/master/exercises/two-fer/src/main/java/Twofer.java) and [csharp](https://github.com/exercism/csharp/blob/master/exercises/two-fer/TwoFer.cs) tracks have errors. And I think we should have them too. Can you make the changes please? @ankorGH

**Comment by ankorGH** [comment]
@SleeplessByte I am currently looking into all the suggestions. Will make changes ASAP.

**Comment by SleeplessByte** [comment]
FYI @ankorGH, since @tejasbubane and I agree, can you change them all (except for `two-fer`) to throw an error?

```javascript
throw new Error('Remove this statement and implement this function')

// e.g.
export class Allergies {
  constructor() {
    throw new Error('Remove this statement and implement this function')
  }
 
  list() {
    throw new Error('Remove this statement and implement this function')
  }

  allergicTo() {
    throw new Error('Remove this statement and implement this function')
  }
}
```

@tejasbubane what do you think of this copy?

**Comment by ankorGH** [comment]
I see [csharp](https://github.com/exercism/csharp/blob/master/exercises/allergies/Allergies.cs) have default  parameter names. Should I add default parameter names or allow the student to name them.

**Comment by tejasbubane** [comment]
I think we should allow the student to name them. What do you think @SleeplessByte ?

**Comment by SleeplessByte** [comment]
> I think we should allow the student to name them. What do you think @SleeplessByte ?

Agreed

**Comment by ankorGH** [comment]
Done with the requested changes.
cc @SleeplessByte @tejasbubane

**Pull request merged**
