### PR TITLE
Adds Alerts Markdown support

### PR DESCRIPTION
**Pull request by cr2007**
With Alerts being supported on GitHub [recently](https://github.com/orgs/community/discussions/16925), this PR adds the updated markdown support to indicate the importance of the text.

Example:
> [!IMPORTANT]  
> We 💙 our community but **this repository does not accept community contributions at this time**.<br>
> There are no active maintainers to review PRs.<br>
> Please read this [community blog post][freeing-maintainers] for details.

Reference: https://github.com/orgs/community/discussions/16925

### CODE REVIEW

**Comment by cr2007** [comment]
I've added it in the forum.

Here is the link for the same: http://forum.exercism.org/t/adds-alerts-markdown-support/9343

**Review by SleeplessByte — APPROVED** [review]

**Comment by SleeplessByte** [comment]
This is blocked by #2321

**Comment by SleeplessByte** [comment]
Could you rebase this on main?

**Comment by SleeplessByte** [comment]
> > Could you rebase this on main?
> 
> Like, I merge this branch to the `main` branch in my fork?

I meant [using git rebase](https://git-scm.com/book/en/v2/Git-Branching-Rebasing) to effectively unwind all the changes, get the latest changes from `main` and then re-apply this branch on top. This way, any changes we have since made to `main` will show up here (including the formatting fixes), without a _merge commit_.

Anyway, I've gone ahead and applied the changes and fixed the formatting of `config.json` (not broken in this PR, but made it all fail).

**Pull request merged**
