### PR TITLE
Change installation links in exercise readme files

### PR DESCRIPTION
**Pull request by RandyCupic**

### CODE REVIEW

**Comment by rchavarria** [comment]
Both #448 and #449 implement #447.

This is a pity, but we need to choose one. I would say #448, only because the PR was submitted before. But, I don't have a strong feeling on which one should be accepted.

Anyway, thanks @RandyCupic and @Evalle for you work, your effort it's highly appreciated.

**Comment by Evalle** [comment]
@rchavarria I see, first come first served :)

**Comment by RandyCupic** [comment]
You're welcome, @rchavarria. I'm so sorry for double PRs, my intention was not to race before Evalle. There were no comments when I came to the issue so I started implementing. Should've check before submitting PR, or left a comment before implementing as well. You can choose which one you want, I don't mind :)

**Comment by tejasbubane** [comment]
Sorry @RandyCupic I did not see this PR and went ahead to merge #449. In order to avoid such situations, I suggest commenting on the issue saying you will work on that before submitting PR.

Sorry again.

**Comment by rchavarria** [comment]
:disappointed: I'm sorry for this situation. There is no procedure to assign a task/issue to people. Sometimes, people open an empty PR. And even doing so, PRs get duplicated. If I'm looking for a issue to solve, I may forgot to look into PRs. Or, not all PRs titles are clear enough, so I end up picking up a issue that is being fix by another person.

If any of you have still energy and wants to contribute, you could choose an exercise listed on #399 and fix some ESLint errors. Pick one randomly, comment on the issue which one you picked, and maybe create an empty PR. That would be a very appreciated work.

Thanks @RandyCupic and @Evalle for contributing :heart:

**Pull request closed without merging**
