### PR TITLE
resolved issue #667

### PR DESCRIPTION
**Pull request by alirezaghey**
Kept "data_structures" since I find it sensible.
Needs to be added to https://github.com/exercism/problem-specifications

### CODE REVIEW

**Comment by SleeplessByte** [comment]
I love this @alirezaghey . Amazing work.

The only thing I would like to change is: can you format the file like before? Each array item on their own line? Apart form that, this is perfect. I personally don't think Matrix is a datastructure "topic" -- could you remove it for now? We'll figure out a _better_ topic and add it to ProblemSpec.

**Comment by alirezaghey** [comment]
Thanks @SleeplessByte. That's encouraging.

Other than in **Matrix**, there or six other occurrences of **data_structures** in the file.
Just to be clear, you are OK with keeping those and want me to only remove it from **Matrix**, right?

**Comment by SleeplessByte** [comment]
Nah, all of them. And let's open a new issue with those 7 that we have to see if there is an alternative!

**Comment by SleeplessByte** [comment]
Thank you for this contribution @alirezaghey

**Pull request merged**
